### PR TITLE
Fix #18

### LINKED ISSUE #18: Remove .d.ts extension from the TS Plugin
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

If you have a project (Nitro for example) with Babel and no TypeScript files it will include the `d.ts` files in the build cycle which fails because `d.ts` files are not compilable whether by the ts-loader nor the fork plugin. We already tested out that if we remove the `.d.ts` in the resolver extensions everything works as expected (also detecting typing issues in Gondel for example).

## Expected behavior

It should not throw an error in case of `d.ts` imports.

## Minimal reproduction of the problem with instructions

1. Check out the latest Nitro version
2. Install Gondel
3. Enable TS in the config
4. Watch the build fail (even if no TS files provided)

## Environment

<pre><code>
Plugin version: *

 
- Node version: 8  
- Platform:  Mac & Windows 

Others:

</code></pre>

### LINKED ISSUE #68: Support Webpack v5
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Does not work with webpack 5

## Expected behavior

Work with webpack 5

## Minimal reproduction of the problem with instructions

Create a webpack 5 project

## What is the motivation / use case for changing the behavior?

Improving webpack 

I'm going to fill this out properly

### PR DESCRIPTION
**Pull request by nemchik**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: link tbd.
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] tooling / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

`.d.ts` files are included in webpack

Issue Number: #18

## What is the new behavior?

`.d.ts` files are not included in webpack

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by nemchik** [comment]
Forgot I need a changelog entry. Not sure the cadence for adding changes for a new version (will have a look at the commit history of the changelog).

**Comment by jantimon** [comment]
This is a breaking change as it will break all apps which use `.d.ts` files

**Comment by nemchik** [comment]
> This is a breaking change as it will break all apps which use `.d.ts` files

I admit I am fairly new to typescript. What would be the purpose of including the `.d.ts` files in a webpack bundle? The readme [here](https://github.com/namics/webpack-config-plugins#use-only-typescript-ts--tsx) says the plugin configs are based on [ts-loader best practices](https://github.com/TypeStrong/ts-loader/blob/master/examples/thread-loader/webpack.config.js) which as far as I can tell do not include the `.d.ts` files in the bundle.

**Comment by nemchik** [comment]
I also now realize i tagged this as fixing the wrong issue. It should be #18 . I will rebase to reword the commit and edit the PR title. My apologies.

**Comment by nemchik** [comment]
@jantimon I had a look at the commit history for the changelog and it really looks like the only changes to the master branch are releases. If this PR were to be accepted should I aim for this PR to be considered a point release? Or is the branch strategy to merge from PRs into a staged branch that gets merged into master as a release at a later time?

**Pull request closed without merging**
