### PR TITLE
feat(font-config-webpack-plugin): add ttf & eot font formats support

### PR DESCRIPTION
**Pull request by Den-dp**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: link tbd.
-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] tooling / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
Error while building project with ttf/eot
```
ERROR in ./node_modules/angular-ui-grid/fonts/ui-grid.ttf 1:0
Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https
://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

ERROR in ./node_modules/angular-ui-grid/fonts/ui-grid.eot 1:2
Module parse failed: Unexpected character ' ' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https
://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

```

## What is the new behavior?

Just works 😉 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information
Despite the fact that eot is IE only thing, I can still imagine that this support should be useful for some projects.

### CODE REVIEW

**Comment by Den-dp** [comment]
I see a bunch of errors for packages that I didn't even touch 🤷‍♂ 
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Comment by Den-dp** [comment]
Actually all above isn't a problem, build fails because of `tsc` error:

https://travis-ci.org/namics/webpack-config-plugins/jobs/606058371#L704-L731
```
> common-config-webpack-plugin@1.4.0 posttest /home/travis/build/namics/webpack-config-plugins/packages/common-config-webpack-plugin
> tsc
../../node_modules/@types/node/index.d.ts:200:11 - error TS2300: Duplicate identifier 'IteratorResult'.
200 interface IteratorResult<T> { }
              ~~~~~~~~~~~~~~
  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.
41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~
  ../../node_modules/@types/node/index.d.ts:200:11
    200 interface IteratorResult<T> { }
                  ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
Found 2 errors.
npm ERR! Test failed.  See above for more details.
lerna ERR! npm test exited 1 in 'common-config-webpack-plugin'
```

Looking into... 🔍

**Comment by Den-dp** [comment]
I had to update `@types/node` to fix this error. The update was minor 10.12.18 -> 10.12.30 so I hope that's not a problem.

**Comment by jantimon** [comment]
Why do you still need those legacy fonts?

**Comment by Den-dp** [comment]
@jantimon we still use the good old bootstrap@3.4 and font-awesome@4.7 for some internal projects. Both use eot and ttf https://unpkg.com/browse/bootstrap@3.4.1/fonts/ https://unpkg.com/browse/font-awesome@4.7.0/fonts/

**Comment by Den-dp** [comment]
Just noticed that even the latest font-awesome package contains odt  https://unpkg.com/@fortawesome/fontawesome-free/webfonts/

**Comment by jantimon** [comment]
The plugin tries to provide best practices and common configuration.
Internet Explorer 10+ support woff

If you want to support IE9 you can easily add loaders for eot or ttf to your webpack config or ask fontawesome why they are still use those old formats.

This package supports also webfont icons however the approach is quite different and probably no replacement to fontawesome: https://www.npmjs.com/package/iconfont-webpack-plugin

**Comment by Den-dp** [comment]
I think this is a reasonable point in terms of prompting the community to go forward and embrace woff2.

And looks like my problem was only in understanding of the main intent of this plugin, because I mistakenly thought this is basically about zero-configuration approach and about reducing "webpack copy-pasta". So I decided to enhance already existing plugin instead of creating a new one. And yes, unfortunately some of my projects aren't on the bleeding edge, and I have to use all these legacy libraries. 🤷‍♂ 

But anyway thanks for this awesome project. Keep up the good work 👍

**Comment by jantimon** [comment]
You are absolutely right the idea is to reduce webpack copy paste - but if you have special requirements it is totally okay to show this special behaviour inside your `webpack.config.js` so that other developers from your team can directly see it.

This project tries to be a preset.
And with most presets you need to adjust them a little bit for example if you are using an eslint preset you might want to fine tune some settings for your needs.

**Comment by Den-dp** [comment]
Whoa, I just found the new `font-config` tag here (and also that this PR isn't closed 😁).

@ernscht if you have some suggestions/preferences on how `font-config` feature should look like - I can help with that.

**Comment by danielkoch** [comment]
@Den-dp: Thank you for your pull request. As @jantimon explains we would like to provide only a "modern stack" and want to avoid "outdated" file formats. If the font plugin does't fit to you needs you can simples remove it (and only this plugin) from your project. See also the handy online helper: https://webpack-config-plugins.js.org/

**Pull request closed without merging**
